# Generated by Django 2.1.2 on 2018-11-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
        ('accounts', '0002_auto_20181108_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='links',
            field=models.ManyToManyField(to='links.Link'),
        ),
    ]
