# Generated by Django 2.1.2 on 2018-11-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181108_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='links',
            field=models.ManyToManyField(blank=True, null=True, to='links.Link'),
        ),
    ]
