# Generated by Django 2.1.2 on 2018-11-09 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_remove_linkdefaults_company'),
        ('accounts', '0006_auto_20181108_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='link_defaults',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='links.LinkDefaults'),
        ),
    ]
