# Generated by Django 2.1.2 on 2018-11-09 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_company_link_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='link_defaults',
        ),
    ]
