# Generated by Django 2.1.2 on 2018-11-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_company_link_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='links',
        ),
    ]
