# Generated by Django 2.1.2 on 2018-11-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20181108_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkdefaults',
            name='company',
        ),
    ]
