# Generated by Django 2.1.2 on 2018-11-09 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_company_link_defaults'),
        ('links', '0003_remove_linkdefaults_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkdefaults',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Company'),
        ),
    ]
