# Generated by Django 2.1.2 on 2018-11-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_linkdefaults_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkdefaults',
            name='ad_base_url',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
