# Generated by Django 2.1.2 on 2018-11-09 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_linkdefaults_ad_base_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkdefaults',
            old_name='ad_link',
            new_name='ad_link_dict',
        ),
        migrations.AlterField(
            model_name='linkdefaults',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Company'),
        ),
    ]
