# Generated by Django 2.1.2 on 2018-11-13 20:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_auto_20181109_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkdefaults',
            name='ad_link_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='make sure "base_url" is included in the json dict'),
        ),
    ]
