# Generated by Django 2.1.2 on 2018-11-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0008_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='type',
            field=models.CharField(choices=[('ad', 'Advertment Link')], default='ad', max_length=15),
            preserve_default=False,
        ),
    ]
