# Generated by Django 2.1.2 on 2018-11-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0009_template_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='company',
            field=models.ManyToManyField(related_name='templates', to='accounts.Company'),
        ),
    ]
