# Generated by Django 2.1.2 on 2018-11-19 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_company_links'),
        ('links', '0010_auto_20181119_1830'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinkDefaults',
            new_name='LinkDefault',
        ),
    ]
