# Generated by Django 2.1.2 on 2018-11-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0011_auto_20181119_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='search_name',
            field=models.CharField(blank=True, choices=[('ad', 'Advertment Link')], help_text='the name for this on a CSV to override a general template', max_length=25),
        ),
        migrations.AlterField(
            model_name='template',
            name='company',
            field=models.ManyToManyField(help_text='The companies who can view this', related_name='templates', to='accounts.Company'),
        ),
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.CharField(choices=[('ad', 'Advertment Link')], help_text='The type of link this template is associated with', max_length=15),
        ),
    ]
