# Generated by Django 2.1.2 on 2019-02-12 15:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0013_auto_20181119_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkdefault',
            name='email_base_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='linkdefault',
            name='email_link_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}', help_text='make sure "base_url" is included in the json dict'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linkdefault',
            name='ad_base_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
