# Generated by Django 2.1.2 on 2019-02-12 19:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0014_auto_20190212_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkdefault',
            name='ad_base_url',
            field=models.CharField(blank=True, help_text='this takes precedent over base_url in ad_link_dict', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='linkdefault',
            name='ad_link_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='make sure "base_url" is included in the json dict'),
        ),
        migrations.AlterField(
            model_name='linkdefault',
            name='email_base_url',
            field=models.CharField(blank=True, help_text='this takes precedent over base_url in email_link_dict', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='linkdefault',
            name='email_link_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='make sure "base_url" is included in the json dict'),
        ),
    ]
